version: '2.1'

services:

  postgresql:
      image: postgres:latest
      volumes:
          - ./docker/data:/var/lib/postgresql/data/pgdata
          - ./docker/tbs:/var/lib/postgresql/data/tbs
#        - ./docker/etc/init.sql:/docker-entrypoint-initdb.d/z_init.sql
#        - ./docker/etc/security.sql:/docker-entrypoint-initdb.d/z_init.sql
      environment:
          - POSTGRES_DB=pentaho
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=admin
          - PGDATA=pgdata
#          - LANG=de_DE.utf8
      ports:
          - 5432:5432


