CREATE TABLE write_test
(
  "Row ID" BIGINT
  , "Order Code" BIGINT
  , "Order Date" TIMESTAMP
  , "Order Priority" VARCHAR(200)
  , "Order Quantity" BIGINT
  , Sales NUMERIC(19, 4)
  , Discount NUMERIC(17, 2)
  , "Ship Mode" VARCHAR(200)
  , Profit NUMERIC(17, 2)
  , "Unit Price" NUMERIC(17, 2)
  , "Shipping Cost" NUMERIC(17, 2)
  , "Customer Code" BIGINT
  , "Customer Name" VARCHAR(200)
  , Province VARCHAR(200)
  , Region VARCHAR(200)
  , "Customer Segment" VARCHAR(200)
  , "Product Code" BIGINT
  , "Product Category" VARCHAR(200)
  , "Product Sub-Category" VARCHAR(200)
  , "Product Name" VARCHAR(200)
  , "Product Container" VARCHAR(200)
  , "Product Base Margin" NUMERIC(17, 2)
  , "Ship Date" TIMESTAMP
)
;

CREATE TABLE STG_ORDERS
(
  "Order Code" BIGINT
  , "Order Priority" VARCHAR(200)
)
;

CREATE TABLE STG_PRODUCTS
(
  "Product Code" BIGINT
  , "Product Category" VARCHAR(200)
  , "Product Sub-Category" VARCHAR(200)
  , "Product Name" VARCHAR(200)
  , "Product Container" VARCHAR(200)
)
;

CREATE TABLE STG_CUSTOMERS
(
  "Customer Code" BIGINT
  , "Customer Name" VARCHAR(200)
  , Province VARCHAR(200)
  , Region VARCHAR(200)
  , "Customer Segment" VARCHAR(200)
)
;


CREATE TABLE DIM_ORDERS
(
  PK_ORDER BIGSERIAL
  , version INTEGER
  , date_from TIMESTAMP
  , date_to TIMESTAMP
  , "Order Code" BIGINT
  , "Order Priority" VARCHAR(13)
)
;CREATE INDEX idx_DIM_ORDERS_lookup ON DIM_ORDERS("Order Code")
;
CREATE INDEX idx_DIM_ORDERS_tk ON DIM_ORDERS(PK_ORDER)
;


CREATE TABLE DIM_PRODUCTS
(
  PK_PRODUCT BIGSERIAL
  , version INTEGER
  , date_from TIMESTAMP
  , date_to TIMESTAMP
  , "Product Code" BIGINT
  , "Product Category" VARCHAR(200)
  , "Product Sub-Category" VARCHAR(200)
  , "Product Name" VARCHAR(200)
  , "Product Container" VARCHAR(200)
)
;CREATE INDEX idx_DIM_PRODUCTS_lookup ON DIM_PRODUCTS("Product Code")
;
CREATE INDEX idx_DIM_PRODUCTS_tk ON DIM_PRODUCTS(PK_PRODUCT)
;


CREATE TABLE DIM_CUSTOMERS
(
  PK_CUSTOMER BIGSERIAL
  , version INTEGER
  , date_from TIMESTAMP
  , date_to TIMESTAMP
  , "Customer Code" BIGINT
  , "Customer Name" VARCHAR(200)
  , province VARCHAR(200)
  , region VARCHAR(200)
  , "Customer Segment" VARCHAR(200)
)
;CREATE INDEX idx_DIM_CUSTOMERS_lookup ON DIM_CUSTOMERS("Customer Code")
;
CREATE INDEX idx_DIM_CUSTOMERS_tk ON DIM_CUSTOMERS(PK_CUSTOMER)
;

CREATE TABLE DIM_DATE
(
  DATE_PK DOUBLE PRECISION
  , YEAR_NUMBER SMALLINT
  , MONTH_NUMBER SMALLINT
  , DAY_OF_YEAR_NUMBER SMALLINT
  , DAY_OF_MONTH_NUMBER SMALLINT
  , DAY_OF_WEEK_NUMBER SMALLINT
  , WEEK_OF_YEAR_NUMBER SMALLINT
  , DAY_NAME VARCHAR(30)
  , MONTH_NAME VARCHAR(30)
  , QUARTER_NUMBER DOUBLE PRECISION
  , QUARTER_NAME VARCHAR(2)
  , YEAR_QUARTER_NAME VARCHAR(32)
  , WEEKEND_IND VARCHAR(1)
  , DAYS_IN_MONTH_QTY SMALLINT
  , DAY_DESC TEXT
  , WEEK_SK DOUBLE PRECISION
  , DAY_DATE TIMESTAMP
  , WEEK_NAME VARCHAR(32)
  , WEEK_OF_MONTH_NUMBER DOUBLE PRECISION
  , WEEK_OF_MONTH_NAME TEXT
  , YEAR_SK DOUBLE PRECISION
  , MONTH_SK DOUBLE PRECISION
  , QUARTER_SK DOUBLE PRECISION
  , DAY_OF_WEEK_SORT_NAME VARCHAR(60)
  , YEAR_SORT_NUMBER VARCHAR(4)
)
;CREATE INDEX idx_DIM_DATE_lookup ON DIM_DATE(DATE_PK)
;
